version: '3.8'

services:
  # Go App Container
  go-app:
    build:
      context: .
    ports:
      - "4040:4040"
    environment:
      - PORT=4040
      - DB_HOST=go-todo-mysql_container2-1
      - DB_USER=root
      - DB_PASS=my-secret-pw
      - DB_PORT=3306
      - DB_DATABASE=gotodo
    depends_on:
      - mysql_container2

  # MySQL Container
  mysql_container2:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=gotodo
      - MYSQL_ROOT_USER=root
    ports:
      - "3308:3308"
