version: '3'

services:
  app:
    build: .
    ports:
      - "4040:4040"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: gotodo
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
